vectors:
  # Yiddish → Gemini embeddings
  # - name: dense_yi_gemini_1536
  #   provider: gemini
  #   model: gemini-embedding-001
  #   task_type: RETRIEVAL_DOCUMENT
  #   dim: 1536
  #   source_field: yi_text
  #   max_input_tokens: 2048
  #   normalize: true

  # Yiddish → Cohere embeddings
  - name: dense_yi_cohere_1536
    provider: cohere
    model: embed-v4.0
    dim: 1536
    source_field: yi_text
    max_input_tokens: 128000
    normalize: true
    input_type: search_document

  # English translations → Gemini embeddings  
  # - name: dense_en_gemini
  #   provider: gemini
  #   model: gemini-embedding-001
  #   task_type: RETRIEVAL_DOCUMENT
  #   dim: 1536
  #   source_field: tr_en_text
  #   max_input_tokens: 2048
  #   normalize: true
